name: Mirror Page

on:
  workflow_dispatch:  # Allows manual triggering of the action

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install curl
        run: |
          sudo apt-get install -y curl

      - name: Mirror the page
        run: |
          url=${{ inputs.url }}
          team_name=${{ inputs.team_name }}
          date=$(date +'%Y-%m-%d')
          month=$(date +'%B')

          # Create month directory if it doesn't exist
          mkdir -p "$month"

          # Fetch the page content
          curl -o "$month/${date}_$(echo $url | sed 's|https\?://||;s|/|_|g;').html" $url
